import sqlite3 as sq


conn=sq.connect("sample_database.db")

cursor=conn.cursor()

cursor.execute('''CREATE TABLE IF NOT EXISTS TEST( ID integer PRIMARY KEY, Product_name TEXT,Amount_sold INTEGER,Sale_date DATE);
''')# i forgot to add AUTO_INCRIMENT to this
cursor.execute('''CREATE TABLE IF NOT EXISTS CUSTOMERS(CUSTOMER_ID INTEGER PRIMARY KEY AUTOINCREMENT,CUSTOMER_NAME TEXT,EMAIL TEXT,PHONE_NUMBER TEXT);''')

cursor.execute('''CREATE TABLE IF NOT EXISTS ORDERS(ORDER_ID INTEGER PRIMARY KEY AUTOINCREMENT,PRODUCT_ID INTEGER,CUSTOMER_ID INTEGER,QUANTITY INTEGER,ORDER_DATE DATE,FOREIGN KEY (PRODUCT_ID) REFERENCES TEST(ID),FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID));''')

cursor.execute('''CREATE TABLE IF NOT EXISTS INVOICE(INVOICE_ID INTEGER PRIMARY KEY AUTOINCREMENT,ORDER_ID INTEGER,TOTAL_AMOUNT REAL,INVOICE_DATE DATE, FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID));''')

conn.commit()
conn.close()

print("done")
